In [5]:
import pandas as pd

df = pd.read_csv("./chunked_press_review.csv")
df['Date'] = pd.to_datetime(df['Date'].apply(lambda x: x.replace(" 00:00:00", "")))
articles = df.groupby(["Title", "Date", "Author", "Newspaper", "Source", "newspaper_type"])['chunks'].apply(lambda x: " ".join(x).replace("  ", " ")).reset_index()
articles = articles.sort_values(["Date"])
articles['time_frame'] = pd.to_datetime(articles['Date'])
articles['Title'] = articles["Title"].apply(lambda x: x.strip())

new_data = pd.read_csv("./extra_times_guadian_data.csv")
articles = pd.concat([articles, new_data], ignore_index=True)

In [6]:
name_map = {"guardian": "The Guardian", "times": "The Times"}
articles['Newspaper'] = articles['Newspaper'].apply(lambda x: name_map.get(x, x) if x in name_map else x)

In [7]:
articles.to_csv("./final_press_review.csv", index=False)

In [1]:
import pandas as pd

articles = pd.read_csv("./final_press_review.csv")

In [2]:
articles['time_frame'] = pd.to_datetime(articles['Date'], format='mixed')

In [3]:
subset = articles[articles.Newspaper == "The Guardian"]

In [4]:
subset[subset.Author == "No author"]

,Title,Date,Author,Newspaper,Source,newspaper_type,chunks,time_frame,Unnamed: 0
10105,Andy Burnham demands NHS contaminated blood in...,2017-4-26,No author,The Guardian,Newspaper site,broadsheet,1/11/2019 Andy Burnham demands NHS contaminate...,2017-04-26,0.0
10106,Contaminated blood survivor_ 'I think they jus...,2017-7-11,No author,The Guardian,Newspaper site,broadsheet,Contaminated blood survivor: 'I think they jus...,2017-07-11,1.0
10107,Theresa May orders contaminated blood scandal ...,2017-7-11,No author,The Guardian,Newspaper site,broadsheet,The Guardian\nTheresa May orders contaminated ...,2017-07-11,2.0
10108,Mongolia's liver cancer crisis_ 'No other coun...,2017-11-7,No author,The Guardian,Newspaper site,broadsheet,Mongolia's liver cancer crisis: 'No other coun...,2017-11-07,3.0
10109,Competition and collaboration to cut the price...,2018-4-11,No author,The Guardian,Newspaper site,broadsheet,The large graphic accompanying your article (T...,2018-04-11,4.0
10110,The Tories' latest campaign tactic_ Blaming La...,2018-5-1,No author,The Guardian,Newspaper site,broadsheet,The Tories' latest campaign tactic? Blaming La...,2018-05-01,5.0
10111,'Treated like pariahs'_ contaminated blood vic...,2018-9-25,No author,The Guardian,Newspaper site,broadsheet,'Treated like pariahs': contaminated blood vic...,2018-09-25,6.0
10112,Britain’s use of contaminated blood was no ‘tr...,2018-4-17,No author,The Guardian,Newspaper site,broadsheet,The latest inquiry must discover how thousands...,2018-04-17,7.0
10113,Zaire notifies deaths,1976-10-23,No author,The Guardian,Newspaper site,broadsheet,Zaire notifies deaths\n\nFrom ROD CHAPMAN\n\nG...,1976-10-23,8.0
10114,Police accused of exaggerating risks of HIV to...,2017-11-17,No author,The Guardian,Newspaper site,broadsheet,The Guardian\n\nPolice accused of exaggerating...,2017-11-17,9.0
10115,Piggyback plague,1984-11-8,No author,The Guardian,Newspaper site,broadsheet,Peggyback Plague\nBy David Dyer\nLondon\n\nThe...,1984-11-08,10.0
10116,Why was contaminated blood allowed to devastat...,2018-9-27,No author,The Guardian,Newspaper site,broadsheet,The Guardian\nWhy was contaminated blood allow...,2018-09-27,11.0
10117,Hepatitis C antiviral drugs are effective _ Le...,2017-7-13,No author,The Guardian,Newspaper site,broadsheet,1/11/2019\nHepatitis C antiviral drugs are eff...,2017-07-13,12.0
10118,Hepatitis could be caused by new virus,1977-1-24,No author,The Guardian,Newspaper site,broadsheet,Hepatitis could be caused by new viruses By ou...,1977-01-24,13.0
10119,Infected blood victims 'may still not know the...,2018-9-24,No author,The Guardian,Newspaper site,broadsheet,Infected blood victims 'may still not know the...,2018-09-24,14.0
10120,NHS tainted blood scandal_ victim payment sche...,2017-3-7,No author,The Guardian,Newspaper site,broadsheet,NHS tainted blood scandal: victim payment sche...,2017-03-07,15.0
10121,'Miracle' hepatitis C drugs costing £30k per p...,2017-6-8,No author,The Guardian,Newspaper site,broadsheet,1/11/2019 'Miracle' hepatitis C drugs costing ...,2017-06-08,16.0
10122,"To tackle the contaminated blood scandal, Brit...",2017-8-1,No author,The Guardian,Newspaper site,broadsheet,"To tackle the contaminated blood scandal, Brit...",2017-08-01,17.0
10123,Britain's contaminated blood scandal_ ‘I need ...,2018-3-3,No author,The Guardian,Newspaper site,broadsheet,Britain's contaminated blood scandal: 'I need ...,2018-03-03,18.0
10124,"HIV, hepatitis, death_ infected blood scandal ...",2018-9-29,No author,The Guardian,Newspaper site,broadsheet,"Red for HIV, yellow for hepatitis, black for d...",2018-09-29,19.0
10125,Contaminated blood scandal victims allowed to ...,2017-9-26,No author,The Guardian,Newspaper site,broadsheet,Contaminated blood scandal victims allowed to ...,2017-09-26,20.0
10126,The Guardian view on the contaminated blood sc...,2017-7-13,No author,The Guardian,Newspaper site,broadsheet,The Guardian view on the contaminated blood sc...,2017-07-13,21.0
10127,Deadly flaws in the US ‘cash for blood’ system...,2017-7-12,No author,The Guardian,Newspaper site,broadsheet,Deadly flaws in the US 'cash for blood' system...,2017-07-12,22.0
10128,Jaundice cases show unexplained increase,1981-8-5,No author,The Guardian,Newspaper site,broadsheet,Jaundice cases show\nunexplained increase\n\nB...,1981-08-05,23.0
10129,Andy Burnham urges Theresa May to rescue conta...,2017-8-31,No author,The Guardian,Newspaper site,broadsheet,"The mayor of Greater Manchester, Andy Burnham,...",2017-08-31,24.0
10130,What is the contaminated blood scandal_ _ Soci...,2017-7-11,No author,The Guardian,Newspaper site,broadsheet,What is the contaminated blood scandal?\n\nKey...,2017-07-11,25.0
10131,Non-profit’s $300 hepatitis C cure as effectiv...,2018-4-12,No author,The Guardian,Newspaper site,broadsheet,Non-profit's $300 hepatitis C cure as effectiv...,2018-04-12,26.0

In [5]:
subset_yearly = subset.groupby(subset['time_frame'].dt.to_period('Y')).size()
subset_yearly

time_frame
1984     5
1989     7
1990     3
1993    11
1994     9
1995    18
1996    25
1997    24
1998    16
1999    22
2000    41
2001    69
2002    54
2003    23
2004    14
2005    34
2006    22
2007    70
2008    13
2009    20
2010    18
2011    11
2012    11
2013    15
2014    27
2015    37
2016    42
2017    47
2018    61
2019    78
2020    64
2021    37
2022    49
2023    41
2024    34
Freq: Y-DEC, dtype: int64

In [2]:
import pandas as pd
nanbh = "Factiva - NANBH"
df = pd.read_csv("./final_press_review.csv")

In [8]:
import pprint
pprint.pprint(df[df.Source == nanbh].chunks.iloc[2])

('Patients waiting for an operation should bank their own blood in case a '
 'transfusion was needed, Dr Lesley Kay, a senior specialist to the Royal '
 'Infirmary, Sunderland, said yesterday.Writing in the latest issue the '
 'British Medical Journal, Dr Kay explained that the proposal was aimed at '
 'avoiding anxiety about the transmission of the Aids virus by blood '
 'transfusion, but it would also relieve worries about possible transmission '
 'of the liver disease non-A non-B hepatitis.The suggestion was described by '
 'Dr Marcela Contreras, director of the North London Blood Transfusion '
 "Service, as 'the ideal scheme for blood donation'.The use of an individual's "
 'own donation for personal transfusion is referred to as autologous blood '
 'transfusion, and it is done in the United States and Australia. Dr Contreras '
 'said, however, it could be arranged only for the wealthy because it meant a '
 'hospital would need to create a blood bank with the individually named '
 'donations.The donations would be made from 35 days before surgery, and a '
 'total of up to eight units (half a litre) of blood could be taken. (c) Times '
 'Newspapers Ltd, 1987')

In [1]:
import pandas as pd
df = pd.read_csv("./final_press_review.csv")

In [5]:
df[df.Title.str.contains("No")]

,Title,Date,Author,Newspaper,Source,newspaper_type,chunks,time_frame,Unnamed: 0
104,No title found,1988-05-04 00:00:00,No author found,The Evening Standard,Newspapers.com,tabloid,TV host Russell Harty slips into coma Russell ...,1988-05-04,NaN
166,On a grand global chase;Norman Sherry,1989-04-01 00:00:00,Alan Franks,The Times,Factiva - HepC,broadsheet,Professor Norman Sherry is as authorized as a ...,1989-04-01,NaN
180,Tribute to Russell Harty;Notebook,1989-06-04 00:00:00,No author in byline,The Sunday Times,Factiva - HepC,broadsheet,RUSSELL HARTY died of hepatitis on June 8 last...,1989-06-04,NaN
189,Architects from another age;North Yemen;Travel,1989-07-09 00:00:00,Dilip Hiro,The Sunday Times,Factiva - HepC,broadsheet,IT happened at our very first camping site a d...,1989-07-09,NaN
203,No title found,1989-08-24 00:00:00,No author found,The Evening Standard,Newspapers.com,tabloid,Hepatitis: Dangers Minimized A blood expert ha...,1989-08-24,NaN
...,...,...,...,...,...,...,...,...,...
10102,No title found,2024-08-17 00:00:00,No author found,Daily Worker / Morning Star,UKPressOnline,other,Confusion over infected blood payouts as victi...,2024-08-17,NaN
10103,No title found,2024-09-13 00:00:00,No author found,Daily Star,UKPressOnline,tabloid,Hope for a chronic virus cure. BOFFINS are clo...,2024-09-13,NaN
10104,No title found,2024-10-31 00:00:00,No author found,Daily Worker / Morning Star,UKPressOnline,other,"Morning Star, Thursday, October 31, 2024 Scotl...",2024-10-31,NaN
10108,Mongolia's liver cancer crisis_ 'No other coun...,2017-11-7,No author,The Guardian,Newspaper site,broadsheet,Mongolia's liver cancer crisis: 'No other coun...,NaN,3.0
10131,Non-profit’s $300 hepatitis C cure as effectiv...,2018-4-12,No author,The Guardian,Newspaper site,broadsheet,Non-profit's $300 hepatitis C cure as effectiv...,NaN,26.0